eureka:
  client:
    fetch-registry: true
    refresh:
      enable: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8100/eureka/
  instance:
    lease-renewal-interval-in-seconds: 60
    instance-id: ${spring.application.name}-${random.uuid}
