eureka:
  client:
    fetch-registry: false
    refresh:
      enable: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8100/eureka/
  instance:
    lease-renewal-interval-in-seconds: 15
